use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Lib tests need no tauri artifacts; skipping lets `cargo test --lib` run
    // while a concurrent `tauri dev` owns the generated files.
    // The skip must re-run this script when the variable flips back: cargo
    // otherwise reuses the skipped output (no embedded manifest/resources) for
    // the next normal build and the exe fails to load (STATUS_ENTRYPOINT_NOT_FOUND,
    // comctl32 v5 lacks TaskDialogIndirect).
    println!("cargo:rerun-if-env-changed=HSP_SKIP_TAURI_BUILD");
    if env::var_os("HSP_SKIP_TAURI_BUILD").is_none() {
        tauri_build::build();
    }
    emit_data_includes();
}

fn emit_data_includes() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let data_root = Path::new(&manifest_dir).join("..").join("data");
    let data_root = data_root
        .canonicalize()
        .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", data_root.display()));

    let mut out = String::new();
    out.push_str("// Auto-generated by engine/build.rs — do not edit.\n\n");

    let singletons: &[(&str, &str)] = &[
        ("AFFIXES_JSON", "affixes.json"),
        ("AFFIX_TAGS_JSON", "affix-tags.json"),
        ("AUGMENTS_JSON", "augments.json"),
        ("CRYSTALS_JSON", "crystals.json"),
        ("GAME_CONFIG_JSON", "game-config.json"),
        ("INCARNATION_NODES_JSON", "incarnation-nodes.json"),
        ("ITEM_GRANTED_SKILLS_JSON", "item-granted-skills.json"),
        ("RUNEWORDS_JSON", "runewords.json"),
        ("SETS_JSON", "sets.json"),
        ("SUBSKILL_TAGS_JSON", "subskill-tags.json"),
    ];
    for (name, file) in singletons {
        let path = data_root.join(file);
        let canonical = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", path.display()));
        out.push_str(&format!(
            "pub const {}: &str = include_str!({:?});\n",
            name, canonical
        ));
        println!("cargo:rerun-if-changed={}", canonical.display());
    }

    let categories: &[(&str, &str)] = &[
        ("CLASSES_JSON", "classes"),
        ("GEMS_JSON", "gems"),
        ("ITEMS_JSON", "items"),
        ("RUNES_JSON", "runes"),
        ("SKILLS_JSON", "skills"),
    ];
    for (const_name, dir) in categories {
        let dir_path = data_root.join(dir);
        let mut files: Vec<PathBuf> = fs::read_dir(&dir_path)
            .unwrap_or_else(|e| panic!("cannot read dir {}: {e}", dir_path.display()))
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
            .collect();
        files.sort();

        out.push_str(&format!("\npub const {}: &[&str] = &[\n", const_name));
        for f in &files {
            let canonical = f
                .canonicalize()
                .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", f.display()));
            out.push_str(&format!("    include_str!({:?}),\n", canonical));
            println!("cargo:rerun-if-changed={}", canonical.display());
        }
        out.push_str("];\n");
        println!("cargo:rerun-if-changed={}", dir_path.display());
    }

    let seasons_dir = data_root.join("seasons");
    out.push_str("\npub const SEASON_PATCHES: &[(&str, &str)] = &[\n");
    if seasons_dir.is_dir() {
        let mut season_dirs: Vec<PathBuf> = fs::read_dir(&seasons_dir)
            .unwrap_or_else(|e| panic!("cannot read dir {}: {e}", seasons_dir.display()))
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        season_dirs.sort();
        for sd in &season_dirs {
            let season_id = sd
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or_else(|| panic!("non-UTF8 season dir name in {}", sd.display()));
            let mut files: Vec<PathBuf> = fs::read_dir(sd)
                .unwrap_or_else(|e| panic!("cannot read dir {}: {e}", sd.display()))
                .filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| {
                    p.file_name()
                        .and_then(|s| s.to_str())
                        .is_some_and(|n| n.ends_with(".patch.json"))
                })
                .collect();
            files.sort();
            for f in &files {
                let canonical = f
                    .canonicalize()
                    .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", f.display()));
                let file_name = f
                    .file_name()
                    .and_then(|s| s.to_str())
                    .unwrap_or_else(|| panic!("non-UTF8 patch file name in {}", f.display()));
                let rel = format!("{season_id}/{file_name}");
                out.push_str(&format!(
                    "    ({:?}, include_str!({:?})),\n",
                    rel, canonical
                ));
                println!("cargo:rerun-if-changed={}", canonical.display());
            }
            println!("cargo:rerun-if-changed={}", sd.display());
        }
        println!("cargo:rerun-if-changed={}", seasons_dir.display());
    }
    out.push_str("];\n");

    let dest = Path::new(&out_dir).join("data_includes.rs");
    fs::write(&dest, out).expect("failed to write data_includes.rs");
}
